package au.edu.unsw.soacourse.loanapprover;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-28T10:22:28.623+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soacourse.unsw.edu.au/loanapprover", name = "loanApprovalPT")
@XmlSeeAlso({au.edu.unsw.soacourse.loandefinitions.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanApprovalPT {

    @WebMethod(action = "http://soacourse.unsw.edu.au/loanapprover/approve")
    @WebResult(name = "approvalMessage", targetNamespace = "http://soacourse.unsw.edu.au/loandefinitions", partName = "loanresp")
    public au.edu.unsw.soacourse.loandefinitions.ApprovalType approve(
        @WebParam(partName = "loanreq", name = "creditInformationMessage", targetNamespace = "http://soacourse.unsw.edu.au/loandefinitions")
        au.edu.unsw.soacourse.loandefinitions.LoanInputType loanreq
    );
}
