package au.edu.unsw.soacourse.founditappserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-27T20:32:52.181+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "FoundITAppServer", 
                  wsdlLocation = "file:/Users/zenglinwang/Documents/Workspace/COMP9322/cs9322-Prac/workspace/FoundITServiceClient/src/main/resources/wsdl/founditappserver.wsdl",
                  targetNamespace = "http://soacourse.unsw.edu.au/founditappserver/") 
public class FoundITAppServer extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soacourse.unsw.edu.au/founditappserver/", "FoundITAppServer");
    public final static QName FoundITAppServerSOAP = new QName("http://soacourse.unsw.edu.au/founditappserver/", "FoundITAppServerSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/zenglinwang/Documents/Workspace/COMP9322/cs9322-Prac/workspace/FoundITServiceClient/src/main/resources/wsdl/founditappserver.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FoundITAppServer.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/zenglinwang/Documents/Workspace/COMP9322/cs9322-Prac/workspace/FoundITServiceClient/src/main/resources/wsdl/founditappserver.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FoundITAppServer(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FoundITAppServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FoundITAppServer() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FoundITAppServer(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FoundITAppServer(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FoundITAppServer(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns FoundITAppPT
     */
    @WebEndpoint(name = "FoundITAppServerSOAP")
    public FoundITAppPT getFoundITAppServerSOAP() {
        return super.getPort(FoundITAppServerSOAP, FoundITAppPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FoundITAppPT
     */
    @WebEndpoint(name = "FoundITAppServerSOAP")
    public FoundITAppPT getFoundITAppServerSOAP(WebServiceFeature... features) {
        return super.getPort(FoundITAppServerSOAP, FoundITAppPT.class, features);
    }

}
