package au.edu.unsw.soacourse.founditappserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-27T20:32:52.176+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soacourse.unsw.edu.au/founditappserver/", name = "foundITAppPT")
@XmlSeeAlso({au.edu.unsw.soacourse.founditappdefinitions.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FoundITAppPT {

    @WebMethod(action = "http://founditappserver.soacourse.unsw.edu.au/check")
    @WebResult(name = "inputMessage", targetNamespace = "http://soacourse.unsw.edu.au/founditappdefinitions", partName = "inputresp")
    public au.edu.unsw.soacourse.founditappdefinitions.InputType check(
        @WebParam(partName = "inputreq", name = "inputMessage", targetNamespace = "http://soacourse.unsw.edu.au/founditappdefinitions")
        au.edu.unsw.soacourse.founditappdefinitions.InputType inputreq
    );
}
